dependencies:
  esp-tflite-micro:
    git: https://github.com/espressif/esp-tflite-micro.git
    version: v1.3.1
  esp32_camera:
    git: https://github.com/espressif/esp32-camera.git
    version: v2.0.15
  mdns:
    git: https://github.com/espressif/esp-protocols.git
    version: mdns-v1.8.2
    path: components/mdns
    rules:
      - if: "idf_version >=5.0"
  espressif/esp_wifi_remote:
    version: 0.10.2
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/eppp_link:
    version: 0.2.0
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/esp_hosted:
    version: 2.0.11
    rules:
      - if: "target in [esp32h2, esp32p4]"
